const TOTAL_BUDGET = 50_000;
const FIELD_MIN = 1;
const FIELD_MAX = 100;
const RESEARCH_CAP = 200_000;
const SCALE_CAP = 7;
const BASE_ATTEMPTS = 20;
const EXTENSION_ATTEMPTS = 5;
const PARTICIPANT_TTL_MS = 3 * 24 * 60 * 60 * 1000;
const MARKET_REFRESH_MS = 20 * 60 * 1000;
const DEFAULT_FAKE_MARKET_SIZE = 40;
const COOKIE_NAME = "signal_outpost_admin";

module.exports = {
  BASE_ATTEMPTS,
  COOKIE_NAME,
  DEFAULT_FAKE_MARKET_SIZE,
  EXTENSION_ATTEMPTS,
  FIELD_MAX,
  FIELD_MIN,
  MARKET_REFRESH_MS,
  PARTICIPANT_TTL_MS,
  RESEARCH_CAP,
  SCALE_CAP,
  TOTAL_BUDGET,
};

